name: letras
description: A new Flutter project.

publish_to: 'none' # This tells pub not to publish to pub.dev.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0
  sqflite_common_ffi_web: any # Agrega esto para que funcione en la web
  path_provider: ^2.0.15
  http: ^1.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
